import type { Pattern, AppSequenceData } from '@ail/common';
import { AutomationGenerator, type GeneratedAutomation } from './base-generator.js';

export class AppleScriptGenerator extends AutomationGenerator {
  readonly type = 'applescript' as const;

  canGenerate(pattern: Pattern): boolean {
    return pattern.type === 'app_sequence';
  }

  generate(pattern: Pattern): GeneratedAutomation {
    const data = JSON.parse(pattern.dataJson) as AppSequenceData;

    const lines = [
      '-- Auto-generated by Ambient Intelligence Layer',
      `-- Pattern: ${pattern.description}`,
      `-- Confidence: ${Math.round((pattern.confidence ?? 0.5) * 100)}%`,
      '',
    ];

    for (const app of data.apps) {
      lines.push(`tell application "${app}"`);
      lines.push('  activate');
      lines.push('end tell');
      lines.push('delay 0.5');
      lines.push('');
    }

    return {
      type: 'applescript',
      name: `Open ${data.apps.join(' + ')}`,
      description: `Opens and activates: ${data.apps.join(', ')} in sequence`,
      scriptContent: lines.join('\n'),
    };
  }

  preview(scriptContent: string): string {
    return scriptContent;
  }
}
