import type { Pattern, AppSequenceData } from '@ail/common';
import { AutomationGenerator, type GeneratedAutomation } from './base-generator.js';

export class PlaywrightGenerator extends AutomationGenerator {
  readonly type = 'playwright' as const;

  canGenerate(pattern: Pattern): boolean {
    // Can generate for app sequences that involve browser apps
    if (pattern.type !== 'app_sequence') return false;
    const data = JSON.parse(pattern.dataJson) as AppSequenceData;
    return data.apps.some(a =>
      ['Google Chrome', 'Safari', 'Firefox', 'Arc', 'Brave Browser', 'Microsoft Edge'].includes(a)
    );
  }

  generate(pattern: Pattern): GeneratedAutomation {
    const data = JSON.parse(pattern.dataJson) as AppSequenceData;

    const script = `// Auto-generated by Ambient Intelligence Layer
// Pattern: ${pattern.description}
// Confidence: ${Math.round((pattern.confidence ?? 0.5) * 100)}%

import { chromium } from 'playwright';

async function run() {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();

  // Navigate to the URLs observed in the workflow
  // TODO: Replace with actual URLs from observation data
${data.apps.filter(a => ['Google Chrome', 'Safari', 'Firefox', 'Arc'].includes(a)).map(
    () => `  await page.goto('https://example.com'); // Replace with observed URL\n  await page.waitForLoadState('networkidle');`
  ).join('\n')}

  // Add your workflow steps here
  // page.click(), page.fill(), page.waitForSelector(), etc.

  await browser.close();
}

run().catch(console.error);
`;

    return {
      type: 'playwright',
      name: `Browser workflow: ${data.apps.join(' + ')}`,
      description: `Playwright script for browser workflow involving ${data.apps.join(', ')}`,
      scriptContent: script,
    };
  }

  preview(scriptContent: string): string {
    return scriptContent;
  }
}
