import type { Pattern, AppSequenceData, TabSwitchData } from '@ail/common';
import { AutomationGenerator, type GeneratedAutomation } from './base-generator.js';

/** Sanitize a value for safe embedding in shell scripts */
function sanitize(value: string): string {
  return value.replace(/[^a-zA-Z0-9 ._\-()]/g, '');
}

/**
 * Generates deterministic bash scripts for Tier 1 patterns.
 * Zero LLM tokens at runtime. Script either works or throws an error.
 */
export class ShellScriptGenerator extends AutomationGenerator {
  readonly type = 'shell' as const;

  canGenerate(pattern: Pattern): boolean {
    return ['app_sequence', 'tab_switching', 'file_workflow'].includes(pattern.type);
  }

  generate(pattern: Pattern): GeneratedAutomation {
    switch (pattern.type) {
      case 'app_sequence':
        return this.generateAppSequence(pattern);
      case 'tab_switching':
        return this.generateTabSwitchFix(pattern);
      case 'file_workflow':
        return this.generateFileWorkflow(pattern);
      default:
        return this.generateGeneric(pattern);
    }
  }

  preview(scriptContent: string): string {
    return scriptContent;
  }

  private generateAppSequence(pattern: Pattern): GeneratedAutomation {
    const data = JSON.parse(pattern.dataJson) as AppSequenceData;
    const lines = [
      '#!/bin/bash',
      'set -euo pipefail',
      '',
      `# Auto-generated by AIL — Tier 1 Hardcoded Script`,
      `# Pattern: ${pattern.description}`,
      `# Confidence: ${Math.round((pattern.confidence ?? 0.5) * 100)}%`,
      `# Observed ${pattern.frequency}x — deterministic, zero-token execution`,
      '',
    ];

    for (const app of data.apps) {
      lines.push(`open -a "${sanitize(app)}"`);
      lines.push('sleep 0.5');
    }

    lines.push('', `echo "Launched: ${data.apps.map(sanitize).join(', ')}"`);


    return {
      type: 'shell',
      name: `Launch: ${data.apps.join(' + ')}`,
      description: `Opens ${data.apps.join(', ')} in sequence. Deterministic shell script — zero runtime cost.`,
      scriptContent: lines.join('\n'),
      executionTier: 1,
    };
  }

  private generateTabSwitchFix(pattern: Pattern): GeneratedAutomation {
    const data = JSON.parse(pattern.dataJson) as TabSwitchData;
    const [app1, app2] = data.apps;

    const script = [
      '#!/bin/bash',
      'set -euo pipefail',
      '',
      `# AIL Tier 1 — Fix frequent switching between ${app1} and ${app2}`,
      `# Opens both side by side instead of constant switching`,
      '',
      `open -a "${app1}"`,
      'sleep 0.3',
      `open -a "${app2}"`,
      '',
      '# Use macOS built-in window tiling (Sequoia+)',
      `echo "Opened ${app1} and ${app2} — arrange side by side for efficiency"`,
    ].join('\n');

    return {
      type: 'shell',
      name: `Side-by-side: ${app1} + ${app2}`,
      description: `Opens ${app1} and ${app2} together to eliminate constant switching (${data.switchCount}x observed).`,
      scriptContent: script,
      executionTier: 1,
    };
  }

  private generateFileWorkflow(pattern: Pattern): GeneratedAutomation {
    const data = JSON.parse(pattern.dataJson) as { paths: string[]; eventTypes: string[] };
    const script = [
      '#!/bin/bash',
      'set -euo pipefail',
      '',
      `# AIL Tier 1 — File workflow automation`,
      `# Pattern: ${pattern.description}`,
      '',
      ...data.paths.map((p, i) =>
        `# Step ${i + 1}: ${data.eventTypes[i] || 'process'} ${p}`
      ),
      '',
      'echo "File workflow completed"',
    ].join('\n');

    return {
      type: 'shell',
      name: `File workflow: ${data.paths[0] || 'files'}`,
      description: pattern.description,
      scriptContent: script,
      executionTier: 1,
    };
  }

  private generateGeneric(pattern: Pattern): GeneratedAutomation {
    return {
      type: 'shell',
      name: `Script: ${pattern.description.substring(0, 40)}`,
      description: pattern.description,
      scriptContent: `#!/bin/bash\nset -euo pipefail\n\n# AIL Tier 1 — ${pattern.description}\necho "TODO: implement automation for ${pattern.type}"`,
      executionTier: 1,
    };
  }
}
